# Generated by Django 5.0 on 2024-02-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportspdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='lab_reports/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedPDF',
        ),
    ]
