# Generated by Django 5.0 on 2024-02-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportspdf', '0002_labreport_delete_uploadedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
