# Generated by Django 5.0 on 2024-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportspdf', '0003_labreport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='name',
            field=models.CharField(default='Default Name', max_length=100, null=True),
        ),
    ]
